### ISSUE TITLE
Redirect all paths containing trailing slashes

### ISSUE THREAD

**Issue by jl-a** [SergioBenitez/Rocket#1212]
(A similar question has been asked before (https://github.com/SergioBenitez/Rocket/issues/702) but only asked about a single path.)

How can I redirect any path containing a trailing slash to the same path but without the slash?

It's standard practice to avoid duplicate URLs with public facing webpages by redirecting them to either all include or all exclude a trailing slash. Manually writing a redirect for every existing path that could contain a trailing slash is generally unfeasible. I would like to match all paths that contain a trailing slash and perform a 301 redirect to the same path, but without the slash.

Including the trailing slash in the request route like so:
```
#[ get( "/<path..>/" ) ]
fn catch_all( path: PathBuf ) -> Redirect {
    ...
}
```
throws the error `paths cannot contain empty segments` which is understandable. Is it possible to match all paths with a trailing slash, and if so, how?

I'm aware I could do this with a proxy server like nginx, but I'm working on a fairly small project and would like to do it in app if possible.

Using Rocket 0.4.2

**Comment by jebrosen** [comment]
> Is it possible to match all paths with a trailing slash, and if so, how?

I believe you will need a fairing in order to check every request like this. Unfortunately request fairings cannot directly respond to a request, so you will need a workaround. One possibility (e.g. as used by `rocket_cors`) is to change the request URI inside of `on_request` to an internal `#[get]` route, which would performs the actual redirect.

Since `on_request` fires for *every* request, you will have to check that `request.uri()` actually has a trailing slash before doing that redirect.

**Comment by kw217** [comment]
Also related to #1198 .

**Comment by SergioBenitez** [comment]
Another option is to implement a custom handler, which can do whatever it wants, that matches on all paths and redirects to a `/`-less path if the path ends in `/`. This would be as simple as:

```rust
impl Handler for Redirector {
    fn handle<'r>(&self, req: &'r Request, _: Data) -> Outcome<'r> {
        if req.uri().path().ends_with('/') {
            Outcome::from(req, Redirect::to(req.uri().to_normalized()))
        } else {
            Outcome::forward(data)
        }
    }
}
```

You'll also need an `Into<Vec<Route>>` implementation. See the [`Handler`](https://api.rocket.rs/v0.4/rocket/trait.Handler.html) docs for a complete example.

**Comment by kratenko** [comment]
I wanna point out that this is not just a SEO issue, but it also breaks all relative paths in a returned html-page. A `<img src="dog.jpg">` at `http://example.org/somewhere` requests `https://example.org/dog.jpg`, at `http://example.org/somewhere/` requests `https://example.org/somewhere/dog.jpg`. So serving the same page under the two uris, with and without trailing slash, really breaks the page!
This just gave me some serious issues, so I think this is more than just a question.

**Comment by kw217** [comment]
Yes, that's why I made a PR! See #1253 .

**Comment by SergioBenitez** [comment]
I believe this is now resolved by #1253! Closing.

**Comment by jebrosen** [comment]
> However, this results in a lifetime error that I can't quite figure out...

@threema-danilo It seems like what you need here is `Redirect::to(fixed_path.to_owned())`.

[&lt;Origin as IntoOwned&gt;::into_owned()](https://api.rocket.rs/master/rocket/http/uri/struct.Origin.html#method.into_owned)

**Comment by threema-danilo** [comment]
@jebrosen unfortunately that doesn't seem to help... I must be overlooking something.

Here's a reproducer: https://github.com/dbrgn/rocket-appendslashes

**Comment by jebrosen** [comment]
@threema-danilo Whoops - I had the right link, but the wrong text. It should have said `Redirect::to(fixed_path.into_owned())`.

**Comment by Glitchy-Tozier** [comment]
I'm still not quite sure how to do this. This is what I have written so far, based on previous comments.

There are no errors, but it seems to only ever get activated when calling the root-route.

```rs
#[derive(Clone)]
struct RemoveSlashes;

#[rocket::async_trait]
impl Handler for RemoveSlashes {
    async fn handle<'r>(
        &self,
        req: &'r rocket::Request<'_>,
        data: rocket::Data<'r>,
    ) -> Outcome<'r> {
        println!(
            "\n\n{}    {}    {}\n\n",
            req.uri().path(),
            req.uri().path().ends_with('/'),
            req.uri().path().to_string().chars().count()
        );
        if req.uri().path().ends_with('/') && req.uri().path().to_string().chars().count() > 1 {
            Outcome::from(
                req,
                Redirect::to(req.uri().clone().into_owned().into_normalized()),
            )
        } else {
            Outcome::forward(data)
        }
    }
}
/* impl From<RemoveSlashes> for Vec<Route> {
    fn from(rs: RemoveSlashes) -> Vec<Route> {
        vec![Route::new(Method::Get, "/", rs)]
    }
} */
impl Into<Vec<Route>> for RemoveSlashes {
    fn into(self) -> Vec<Route> {
        vec![Route::new(Method::Get, "/", self)]
    }
}

/// The analog to the usual `fn main()`.
#[launch]
fn rocket() -> _ {
    let rocket_build = rocket::build()
        .mount("/", RemoveSlashes)
        . …other routes
}
```

**Comment by levkk** [comment]
Ran into this today as well, thank you for the solution! It would be cool to include this as a config. This is a very common SEO optimization and other frameworks, e.g. Django, have this option.

**Comment by SergioBenitez** [comment]
> I also ran into this today.  It looks like something changed recently in Rocket so that routing that used to support extraneous trailing `/` no longer support it.  Was running into a bunch of 404s after updating rocket and it turned out this was the cause. 

This changed recently on master, yes. It resolves this issue globally. See the "reconsider normalization" issue for more.

**Comment by Glitchy-Tozier** [comment]
I assume that's the issue: https://github.com/SergioBenitez/Rocket/issues/2512
