### ISSUE TITLE
Build failures in Nightly due to Proc macro API 1.2 changes

### ISSUE THREAD

**Issue by tirkarthi** [SergioBenitez/Rocket#646]
Bug report : 

Project fails with Nightly compiler due to the recent proc macro API changes made that renames some of the components. It seems the release of proc macros 2 library with the changes already merged will fix the issue. I searched for issues here and couldn't find anything related to this. Hence I am opening this as a reminder to upgrade dependency. Feel free to close this if it's tracked elsewhere or irrelevant. 

Upstream rustc issue reference : https://github.com/rust-lang/rust/pull/50473#issue-186182501
Upstream proc macros 2 PR (merged) : https://github.com/alexcrichton/proc-macro2/pull/90
Build failure : https://travis-ci.org/SergioBenitez/Rocket/jobs/381529609

Thanks for the library.

**Comment by tirkarthi** [comment]
0.4.3 released with the changes. Ref : https://github.com/alexcrichton/proc-macro2/tree/0.4.3

**Comment by jebrosen** [comment]
`quote` 0.6 and `syn` 0.14 were just released 9 hours ago, so this should be possible to fix now. @SergioBenitez have you started work on this migration or would a PR be helpful?

**Comment by SergioBenitez** [comment]
@jebrosen I would love a PR here. The changes necessary should be minimal.

**Comment by SergioBenitez** [comment]
Fixed in https://github.com/SergioBenitez/Rocket/commit/00dd6912528ad82357f01170b158c012b7acfbea.

**Comment by tsathishkumar** [comment]
Will there be a new version of Rocket with build fixes?

**Comment by jebrosen** [comment]
@tsathishkumar: This issue was only in the `master` branch of Rocket, which has now been fixed.

**Comment by tsathishkumar** [comment]
@jebrosen I'm using rocket version 0.3.11 in my code and the build is failing. So I was wondering if there will be a new version coming out soon. Thanks for the response.

**Comment by jebrosen** [comment]
@tsathishkumar if a `cargo update` does not resolve the build failures, please file a new issue with more details.

**Comment by tsathishkumar** [comment]
The issue still persists, because 0.3.11 was built before your fix. I'm going to temporarily point to git branch and build my project and wait for the next release.
